// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leksahrohrevetqzobxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla3NhaHJvaHJldmV0cXpvYnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzE2MTAsImV4cCI6MjA3MjYwNzYxMH0.zx8s6GXfvBLjVIzseEtuNAMYUCw6NoDJ776eCAUAc48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});